name: Feature Validation

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Test OS
        run: |
          if [ "$RUNNER_OS" != "Linux"]; then
            echo "Not running on Linux. Failing."
            exit 1
          fi
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make update
      - name: Test Python version
        run: |
           if [[ "$python_version" != "Python 3.10"* && $python_version != "Python 3.11"*]]; then
             echo "This requires python version 3.10 or 3.11 the current version is : $python_version"
             exit 1
           fi
      - name: Test with pytest
        run: |
          make test
